### ISSUE TITLE
Rewrite template

### ISSUE THREAD

**Issue by aanosh** [atomictech/xlsx-write-stream#3]
Hello, I am using this extension, is there any possibility to rewrite teplate dynamically (I need default sheet2 as well)?

ps. I tried pipe the fs stream, but with no luck.

**Comment by Jule-** [comment]
Hello, actually this is not possible to handle 2 sheets, the focus was really on CSV like replacement.

Nevertheless, I think it could be done by adding some logic to the stream transform like sending to the pipe specific "command" like "new sheet" and catch this in order to end sheet1 and append sheet2 to the zip stream and redirect the input stream to this new sheet stream... Plus the need to handle properly different headers by sheets etc.

I am not planning to do it by myself, but if you want to do a PR, you are welcome and I can help you answering your questions. :slightly_smiling_face: 

A good starting point for understanding what is done under the hood:
https://github.com/atomictech/xlsx-write-stream/blob/14600fd47e01c87f5e35303ab76c77451e6b5f5d/src/XLSXWriteStream.js#L59-L89

**Comment by aanosh** [comment]
thanks, I will make a PR if I am able to acomplish  :)
