### ISSUE TITLE
Is it possible to set styleDef per column/per cell?

### ISSUE THREAD

**Issue by dv-anatolyg49** [atomictech/xlsx-write-stream#5]
If it is not possible then how hard do you think it would be to implement it. 
Where would be a good place to start looking and what are the difficulties to expect if I try to implement it by myself?

**Comment by Jule-** [comment]
Hi,

Actually I am not sure what you are trying to achieve because the aim of this feature is to "type style" correctly the cells accordingly to the javascript type in input. Thus if you want to "type style" a column/cell what you have to do is just to send data with the correct type.

If you are talking about styling cells/column with background color or stuff like that then this is not made for this purpose. It should be doable to add API to the lib in order to get more fine configuration over the styles templates and to tweak styles depending on the column/cell...
...but this lib wasn't made to put lot of styling, the focus is on performance, size efficiency and data type correctness, so it could be hard to maintain the API spirit "javascript data type" => "data type style". Knowing that it should be a bit of work to include this in the process. If you implement this kind of feature it should be an opt in and totally transparent if not opted in. Another fact you should know is that the format documentation is not that easy to read so it should be many hours digging in order to know exactly how you can achieve what you want in the openxml format (my advice, do it in a empty/dummy Excel then save and unzip in order to see what's going on under the hood).

To conclude my feeling is that it could be a bit of pain to implement, if you see what I mean, but not impossible.

Starting point:
- https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet?view=openxml-2.8.1
- https://github.com/atomictech/xlsx-write-stream/blob/master/src/templates/styles.js
- https://github.com/atomictech/xlsx-write-stream/blob/master/src/templates/cell.js

**Comment by dv-anatolyg49** [comment]
Thank you @Jule- , it is very helpful especially the `cell.js` bit. 
What we need is to set different styles for numeric columns within the same document. E.g. one col to have 2 signs after floating point and another to have 1.
We will decide if we want to do this at all and how we want to go about it.
